# -*- coding: utf-8 -*-
"""project-minor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gOaeDnVudJc3DoNy6cbRXVq04ahksEq9
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

df=pd.read_csv("/content/drive/MyDrive/air-quality-india.csv")
df

df.info()



df.describe().T

df.groupby("Day")["Hour"].sum()

df["PM2.5"].max()

plt.scatter(x=df["Year"],y=df["PM2.5"])
plt.title("Scatter between Year and PM2.5",c="k",fontsize=19)
plt.xlabel("Year",fontsize=15,c="r")
plt.ylabel("PM2.5",fontsize=15,c="g")
plt.show()

df.hist(bins=30,figsize=(10,10))
plt.show()

data=df.drop(["Timestamp","Hour"],axis=1)
data

x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

x

y

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2,shuffle=True)

print("x_train shape",x_train.shape)
print("x_test shape",x_test.shape)
print("y_train shape",y_train.shape)
print("y_test shape",y_test.shape)

x_train

x_test

y_train

y_test

rf=RandomForestRegressor(max_depth=7,n_estimators=9,random_state=42)
rf.fit(x_train,y_train)

rf.score(x_train,y_train)

mse_score_rf=cross_val_score(estimator=rf,X=x_train,y=y_train,cv=6,n_jobs=4,scoring="neg_mean_squared_error")

mse_score_rf=-1*mse_score_rf
mse_score_rf

y_pred_rf=cross_val_predict(estimator=rf,X=x_train,y=y_train,cv=6,n_jobs=5,method="predict")

y_pred_rf

mse_rf=mean_squared_error(y_train,y_pred_rf)
mse_rf

rmse_rf=np.sqrt(mse_rf)
rmse_rf

rf_accuracy=rf.score(x_test,y_test)
rf_accuracy

lr=LinearRegression()
lr.fit(x_train,y_train)

lr.score(x_train,y_train)

mse_score_lr=cross_val_score(estimator=lr,X=x_train,y=y_train,cv=5,n_jobs=3,scoring="neg_mean_squared_error")
mse_score_lr= 1*mse_score_lr
mse_score_lr

y_pred_lr=cross_val_predict(estimator=lr,X=x_train,y=y_train,cv=9,n_jobs=8)

y_pred_lr

mse_lr=mean_squared_error(y_train,y_pred_lr)
mse_lr

rmse_lr=np.sqrt(mse_lr)
rmse_lr

lr_accuracy=lr.score(x_test,y_test)
lr_accuracy



dt = DecisionTreeRegressor(max_depth=9)
dt.fit(x_train,y_train)

dt.score(x_train,y_train)

y_pred_dt=cross_val_predict(estimator=dt,X=x_train,y=y_train,cv=9,n_jobs=8)

y_pred_dt

mse_dt=mean_squared_error(y_train,y_pred_dt)
mse_dt

rmse_dt=np.sqrt(mse_dt)
rmse_dt

dt_accuracy=dt.score(x_test,y_test)
dt_accuracy

print("The accuracy of the models are listed below ")
print(f"The accuracy of Random Forest Regressor is {rf_accuracy}")
print(f"The accuracy of Linear Regression is {lr_accuracy}")
print(f"The accuracy of Decision Tree Regessor is {dt_accuracy}")





models = ['Random Forest', 'Linear Regression', 'Decision Tree']
scores = [rf_accuracy, lr_accuracy, dt_accuracy]

plt.figure()
plt.bar(models, scores)
plt.xlabel("Models")
plt.ylabel("R² Score")
plt.title("Comparison of Regression Model Performance")
plt.ylim(0, 1)

plt.show()

models = ["Random Forest", "Linear Regression", "Decision Tree"]

rmse_scores = [rmse_rf, rmse_lr, rmse_dt]

plt.figure()
plt.bar(models, rmse_scores)
plt.xlabel("Models")
plt.ylabel("RMSE")
plt.title("RMSE Comparison of Regression Models")
plt.show()

models = ["Random Forest", "Linear Regression", "Decision Tree"]
mse_scores = [mse_rf, mse_lr, mse_dt]

plt.figure()
plt.bar(models,mse_scores)
plt.xlabel("Models")
plt.ylabel("MSE")
plt.title("MSE Comparison of Regression Models")
plt.show()

print("The Decision Tree Regressor achieved the highest R² score, indicating the best predictive performance. Random Forest also performed well, while Linear Regression showed very poor performance, suggesting that the data has a non-linear relationship")